### ISSUE TITLE
order of load

### ISSUE THREAD

**Issue by iMashhadi** [meziantou/Meziantou.AspNetCore.BundleTagHelpers#1]
Hi
My problem is the order of load files after bundling.
When i use that, order of files not comply.
How can i fix it ?

**Comment by meziantou** [comment]
The order should be as defined in the [`bundleconfig.json` file](https://github.com/madskristensen/BundlerMinifier#bundleconfigjson).

````
[
  {
    "outputFileName": "output/app.js",
    "inputFiles": [
      "input/first.js",  // first file in the bundle
      "input/second.js", // second file in the bundle
    ]
  }
]
````

**Comment by iMashhadi** [comment]
Yes i know, it is but when i see files in debugger it's not in order.
for example i get this error "jQuery is not defined" because jquery load after that. jquery it's loaded
