### ISSUE TITLE
Merging this into BundlerMinifier

### ISSUE THREAD

**Issue by rockstardev** [meziantou/Meziantou.AspNetCore.BundleTagHelpers#3]
Hey meziantou,

I've been working with Mads on BundlerMinifier on sprucing up that repo as you can see from latest commits:

https://github.com/madskristensen/BundlerMinifier/commits/master

One of the things I wanted to do is integrate what you've done here into BundlerMinifier in some form so that people have natural support in ASP.NET Core. Do you have time to collaborate on this? Any thoughts? 

Let me know and talk soon I hope.

**Comment by rockstardev** [comment]
Well you sure are quick on draw here on Github ;)

**Comment by meziantou** [comment]
Hi,

I think it's a good idea to add something derived from this repo into the BundlerMinifier repository!

I will have time to contribute on this in the next few days. Do you have any idea of how we should process? Do you want me to create a PR with the tag helper?

**Comment by rockstardev** [comment]
The way I would do it is to just merge it as is as subfolder / project under src:

https://github.com/madskristensen/BundlerMinifier/tree/master/src

And then publish NuGet under BundlerMinifier.TagHelpers and update documentation here to point to what you've done:

https://github.com/madskristensen/BundlerMinifier/wiki#aspnet-helpers

Also we need to figure out if there is anything you wanted to add functionality wise before we do that. Plus if you are interested in long term maintenance of that part of project so that I can talk with Mads so you are added to repo as direct contributor.

**Comment by meziantou** [comment]
Maybe I should change the namespace of the project to `BundlerMinifier.TagHelpers` (and the name of the project accordingly). Indeed, I don't expect people to discover the namespace `Meziantou.AspNetCore.BundleTagHelpers` after installing the package `BundlerMinifier.TagHelpers`.

I think the code should be under a folder named `BundlerMinifierTagHelpers` or `BundlerMinifier.TagHelpers` to respect the naming strategy of the repo.

I don't think I'll add new functionalities at the moment. Let me know if you have any idea of something that should be added or changed to this project.

@madskristensen Do you have any feedback about this?

**Comment by rockstardev** [comment]
Yes, I would create `BundlerMinifier.TagHelpers` subfolder here:

https://github.com/madskristensen/BundlerMinifier/tree/master/src

And then include code and refactor namespaces. I need to talk with Mads on then setting up process for generating NuGets and increasing visibility of what you've done. I think large part of that will be having `BundlerMinifier.TagHelpers` as the name of the package. People are more likely to download and use what you've done once they see it part of `BundlerMinifier` package.

One feature we'll definitely need is ability to declare and parse "mixed" bundles. Right now it's up to developer to declare separate JS/CSS bundles. The problem is that this introduces disconnect since components you include in project are almost always combination of JS/CSS. So we need to be able to support format like:

	[
	  {
	    "outputFiles": ["wwwroot/bundles/bundle.css","wwwroot/bundles/bundle.js"],
	    "inputFiles": [
		// bootstrap
		"wwwroot/bs/bootstrap.css",
		"wwwroot/bs/bootstrap.js",
		// component 1
		"wwwroot/c1/c1.css",
		"wwwroot/c1/c1.js",
		// so on...
	    ]
	  }
	]

And then it's up to first `BundlerMinifier` and later `TagHelper` to be able to parse this format and output separate CSS and separate JS bundles.

**Comment by meziantou** [comment]
I've created a PR: https://github.com/madskristensen/BundlerMinifier/pull/360, so maybe we can continue the discussion in the comments of the PR.

**Comment by rockstardev** [comment]
OK, we'll likely split it:

1. Merge this into main repo, rename namespaces, setup NuGet build with Mads and publish that
2. Add new features.

Sending you comments as soon as I review.
